### ISSUE TITLE
Encrypted Video Playback  Error with Exoplayer - AES/CTR/NoPadding

### ISSUE THREAD

**Issue by kanujgit** [moagrius/EncryptedExoPlayerDemo#11]
in my project i am using .mov video format. and i simply download the video in encrypted  and save the dummy name test.mov  but when we are decrypt the video and play through exoplayer it gives the error which is mention below 

E/ExoPlayerImplInternal: Playback error.

 com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:441)

        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:428)

        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:920)

        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:503)

        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:557)

        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)

        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:158)
        at android.os.HandlerThread.run(HandlerThread.java:61)

     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [1280, 720, -1.0], [-1, -1])

**Comment by moagrius** [comment]
does it work unencrypted?

**Comment by kanujgit** [comment]
Yes, it is work in unEncrypted or from URL

**Comment by moagrius** [comment]
Hm not sure.  That error means it's unable to decode the file (unable to decode, not decrypt - but that could very well mean bad encryption).

Not sure I can help much; good luck!
