### ISSUE TITLE
com.google.android.exoplayer2.source.UnrecognizedInputFormatException

### ISSUE THREAD

**Issue by anuragappsbee** [moagrius/EncryptedExoPlayerDemo#15]
When I tried to play an encrypted file using the same codes of your facing this issue.

`ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:973)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:891)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by moagrius** [comment]
That's usually because it's being encrypted or decrypted wrong, but could
also mean your source file is not supported (not mp4 or similar)

**Comment by nileshbborkar** [comment]
i facing same issue, first time it plays right but after that it does not play at all.

**Comment by EngineerDanny** [comment]
First time it plays because the key and iv are generated by `SecureRandom` which is stored in memory are used for both encryption and decryption.

However when you restart the app, new key and iv is generated by `SecureRandom` so it will not match the old ones used to encrypt the file.

A fix to this issue will be to change and explicitly define your keys. And use the same keys to encrypt and decrypt the file.


   ` byte[] key = { 65, 66, 67,65, 66, 67,65, 66, 67,65, 66, 67,65, 66, 67,16};`
   ` byte[] iv = { 65, 66, 67,65, 66, 67,65, 66, 67,65, 66, 67,65, 66, 67,16};`
