### ISSUE TITLE
Video gives error after few minutes

### ISSUE THREAD

**Issue by chnouman** [moagrius/EncryptedExoPlayerDemo#9]
`2018-12-30 16:18:24.750 15013-2510/com.aylive.ayboxoffice E/ExoPlayerImplInternal: Source error.
    java.io.EOFException
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:252)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:76)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:431)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:153)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:635)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)`

don't know why this is happening.

**Comment by moagrius** [comment]
can't be sure from that stacktrace but i'm guessing the file is encrypted incorrectly.  remember that you need to encrypt a *clear* file, for playback, then comment out that piece.

**Comment by chnouman** [comment]
@moagrius sorry for your time you are correct that was file issue while downloading it gets stop anywhere which causes the issue. Your work is perfect thanks for sharing.

**Comment by moagrius** [comment]
NP!
